name: Renovate

on:
  schedule:
    - cron: '0 3 * * *'  # chaque nuit à 3h
  workflow_dispatch:

jobs:
  renovate:
    runs-on: codeberg-small
    container:
      image: renovate/renovate
    steps:
      - name: Run Renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: https://codeberg.org
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_REPOSITORIES: leuwen-lc/rhdemo
        run: renovate
