DROP TABLE IF EXISTS employes;
 
CREATE TABLE employes (
  id BIGSERIAL PRIMARY KEY,  
  prenom VARCHAR(250) NOT NULL,
  nom VARCHAR(250) NOT NULL,
  mail VARCHAR(250) NOT NULL,
  adresse VARCHAR(500)
);
 
INSERT INTO employes (prenom, nom, mail, adresse) VALUES
  ('Laurent', 'GINA', 'laurentgina@mail.com', '123 Rue de la Paix, 75001 Paris'),
  ('Sophie', 'FONCEK', 'sophiefoncek@mail.com', '456 Avenue des Champs, 69000 Lyon'),
  ('Agathe', 'FEELING', 'agathefeeling@mail.com', '789 Boulevard Central, 13000 Marseille'),
  ('Pierre', 'ANDRE', 'pierre.andre@mail.com', '657 Impasse du Centre, 69003 Lyon'),
  ('Daniel', 'PETIT', 'daniel.petit@mail.com', '171 Impasse de la Colline, 35000 Rennes'),
  ('Alice', 'DUMAS', 'alice.dumas@mail.com', '989 Impasse de la Mairie, 87100 Limoges'),
  ('Elena', 'POPA', 'elena.popa@mail.com', '912 Boulevard de la Place, 75011 Paris'),
  ('Benjamin', 'OLIVIER', 'benjamin.olivier@mail.com', '636 Chemin Notre-Dame, 14000 Caen'),
  ('Bruno', 'BLANCHARD', 'bruno.blanchard@mail.com', '13 Route de Verdun, 33100 Bordeaux'),
  ('Jorge', 'GALLO', 'jorge.gallo@mail.com', '501 Route des Écoles, 45100 Orléans'),
  ('Fabrice', 'BOURGEOIS', 'fabrice.bourgeois@mail.com', '494 Rue des Lilas, 14000 Caen'),
  ('Brigitte', 'ROGER', 'brigitte.roger@mail.com', '264 Boulevard du Marché, 59200 Lille'),
  ('Laura', 'BOYER', 'laura.boyer@mail.com', '116 Rue Georges Pompidou, 75018 Paris'),
  ('Éliane', 'PIERRE', 'eliane.pierre@mail.com', '500 Boulevard du Parc, 75018 Paris'),
  ('Thierry', 'FONTAINE', 'thierry.fontaine@mail.com', '936 Place de la Paix, 75010 Paris'),
  ('Stéphane', 'MULLER', 'stephane.muller@mail.com', '902 Place de la Victoire, 63100 Clermont-Ferrand'),
  ('Denis', 'VIDAL', 'denis.vidal@mail.com', '280 Avenue du Centre, 75017 Paris'),
  ('Samuel', 'DUVAL', 'samuel.duval@mail.com', '126 Avenue de la Place, 75018 Paris'),
  ('Léa', 'DUPUIS', 'lea.dupuis@mail.com', '861 Allée François Mitterrand, 13006 Marseille'),
  ('Hélène', 'SCHMITT', 'helene.schmitt@mail.com', '920 Impasse Clémenceau, 69006 Lyon'),
  ('Raphaël', 'PICARD', 'raphael.picard@mail.com', '853 Boulevard des Champs, 14000 Caen'),
  ('Daniel', 'BONNET', 'daniel.bonnet@mail.com', '860 Impasse Nationale, 75005 Paris'),
  ('Baptiste', 'LACROIX', 'baptiste.lacroix@mail.com', '307 Boulevard Rousseau, 92000 Nanterre'),
  ('Émilie', 'BONNET', 'emilie.bonnet@mail.com', '824 Chemin des Lilas, 92000 Nanterre'),
  ('Alain', 'BRUNET', 'alain.brunet@mail.com', '187 Chemin de la Rivière, 59000 Lille'),
  ('Anastasia', 'MANSOUR', 'anastasia.mansour@mail.com', '624 Boulevard de l''Église, 83100 Toulon'),
  ('Laura', 'DUPUIS', 'laura.dupuis@mail.com', '799 Impasse des Peupliers, 38100 Grenoble'),
  ('Antoine', 'ROUX', 'antoine.roux@mail.com', '524 Impasse Notre-Dame, 59800 Lille'),
  ('François', 'BERNARD', 'francois.bernard@mail.com', '777 Avenue de la Fontaine, 75019 Paris'),
  ('Rachid', 'GONZALEZ', 'rachid.gonzalez@mail.com', '188 Chemin Voltaire, 75001 Paris'),
  ('Véronique', 'DUMAS', 'veronique.dumas@mail.com', '591 Avenue des Tilleuls, 63100 Clermont-Ferrand'),
  ('Valentin', 'BLANC', 'valentin.blanc@mail.com', '402 Impasse du Général de Gaulle, 75003 Paris'),
  ('Virginie', 'RICHARD', 'virginie.richard@mail.com', '678 Avenue Clémenceau, 49000 Angers'),
  ('Jose', 'CONTI', 'jose.conti@mail.com', '212 Cours de Verdun, 75002 Paris'),
  ('Gabriel', 'BLANCHARD', 'gabriel.blanchard@mail.com', '808 Route du 11 Novembre, 06100 Nice'),
  ('Anne', 'ROGER', 'anne.roger@mail.com', '808 Route du Commerce, 34070 Montpellier'),
  ('Noémie', 'PERRIN', 'noemie.perrin@mail.com', '57 Cours de la République, 49100 Angers'),
  ('Christophe', 'JOLY', 'christophe.joly@mail.com', '493 Rue Rousseau, 75008 Paris'),
  ('Yves', 'LEMAIRE', 'yves.lemaire@mail.com', '401 Boulevard de la Fontaine, 34070 Montpellier'),
  ('André', 'MASSON', 'andre.masson@mail.com', '66 Impasse Victor Hugo, 94200 Ivry-sur-Seine'),
  ('Sarah', 'LACROIX', 'sarah.lacroix@mail.com', '301 Avenue de l''Avenir, 86000 Poitiers'),
  ('François', 'MERCIER', 'francois.mercier@mail.com', '562 Cours Clémenceau, 87100 Limoges'),
  ('Lucie', 'MASSON', 'lucie.masson@mail.com', '493 Avenue des Érables, 75008 Paris'),
  ('Salma', 'BRUNO', 'salma.bruno@mail.com', '928 Avenue des Peupliers, 34070 Montpellier'),
  ('Jacques', 'MERCIER', 'jacques.mercier@mail.com', '670 Allée du Moulin, 29280 Brest'),
  ('Martine', 'BOYER', 'martine.boyer@mail.com', '58 Chemin Molière, 06000 Nice'),
  ('Simone', 'GUERIN', 'simone.guerin@mail.com', '150 Chemin Molière, 37000 Tours'),
  ('André', 'PERRIN', 'andre.perrin@mail.com', '700 Cours François Mitterrand, 86000 Poitiers'),
  ('Thierry', 'BERNARD', 'thierry.bernard@mail.com', '811 Chemin de la Poste, 63100 Clermont-Ferrand'),
  ('René', 'BOYER', 'rene.boyer@mail.com', '708 Impasse de la Place, 13002 Marseille'),
  ('Léo', 'ANDRE', 'leo.andre@mail.com', '918 Rue du Port, 69002 Lyon'),
  ('Pierre', 'ROBIN', 'pierre.robin@mail.com', '111 Avenue de l''Église, 34000 Montpellier'),
  ('Isabelle', 'DUVAL', 'isabelle.duval@mail.com', '236 Boulevard Victor Hugo, 87000 Limoges'),
  ('Victor', 'OLIVIER', 'victor.olivier@mail.com', '924 Impasse de la Place, 17000 La Rochelle'),
  ('Monique', 'FONTAINE', 'monique.fontaine@mail.com', '263 Chemin de la Liberté, 94000 Créteil'),
  ('André', 'PERRIN', 'andre.perrin@mail.com', '313 Chemin des Roses, 67100 Strasbourg'),
  ('Quentin', 'GARNIER', 'quentin.garnier@mail.com', '684 Chemin de la Rivière, 06100 Nice'),
  ('Monique', 'BOURGEOIS', 'monique.bourgeois@mail.com', '289 Avenue du Marché, 59000 Lille'),
  ('Isabelle', 'COLIN', 'isabelle.colin@mail.com', '985 Cours du Moulin, 49000 Angers'),
  ('Raphaël', 'RENARD', 'raphael.renard@mail.com', '676 Rue La Fontaine, 42000 Saint-Étienne'),
  ('Boris', 'ROSSI', 'boris.rossi@mail.com', '214 Place du Marché, 59200 Lille'),
  ('Hugo', 'ROUX', 'hugo.roux@mail.com', '411 Place du Marché, 75016 Paris'),
  ('Sébastien', 'NICOLAS', 'sebastien.nicolas@mail.com', '534 Place de la Victoire, 06000 Nice'),
  ('Guillaume', 'MARCHAND', 'guillaume.marchand@mail.com', '94 Place des Lilas, 13002 Marseille'),
  ('Marie', 'RENARD', 'marie.renard@mail.com', '284 Boulevard Saint-Michel, 31100 Toulouse'),
  ('Valentin', 'DUPUIS', 'valentin.dupuis@mail.com', '857 Place du Château, 93200 Saint-Denis'),
  ('Leila', 'BENMOHAMED', 'leila.benmohamed@mail.com', '757 Place de la Liberté, 75016 Paris'),
  ('Sébastien', 'FOURNIER', 'sebastien.fournier@mail.com', '93 Allée de l''Église, 31200 Toulouse'),
  ('Nathalie', 'DUFOUR', 'nathalie.dufour@mail.com', '915 Allée Rousseau, 75017 Paris'),
  ('Maxime', 'VIDAL', 'maxime.vidal@mail.com', '38 Cours du Commerce, 76100 Rouen'),
  ('Nathalie', 'LAURENT', 'nathalie.laurent@mail.com', '737 Route de la Victoire, 76000 Rouen'),
  ('Stéphane', 'SCHMITT', 'stephane.schmitt@mail.com', '494 Rue du Moulin, 87100 Limoges'),
  ('Caroline', 'LEMOINE', 'caroline.lemoine@mail.com', '532 Avenue du Général de Gaulle, 75020 Paris'),
  ('Olivier', 'RICHARD', 'olivier.richard@mail.com', '640 Place de la République, 45100 Orléans'),
  ('Patricia', 'DUPONT', 'patricia.dupont@mail.com', '924 Cours de la Victoire, 75018 Paris'),
  ('Romain', 'DUFOUR', 'romain.dufour@mail.com', '446 Rue Victor Hugo, 75002 Paris'),
  ('Dominique', 'GIRARD', 'dominique.girard@mail.com', '977 Boulevard des Lilas, 75015 Paris'),
  ('Vincent', 'RENARD', 'vincent.renard@mail.com', '364 Route du Port, 42000 Saint-Étienne'),
  ('Quentin', 'COLIN', 'quentin.colin@mail.com', '664 Route Rousseau, 93000 Bobigny'),
  ('Catherine', 'BONNET', 'catherine.bonnet@mail.com', '794 Cours de la Paix, 37100 Tours'),
  ('Sylvie', 'LAURENT', 'sylvie.laurent@mail.com', '892 Avenue du Général de Gaulle, 33100 Bordeaux'),
  ('Victor', 'SIMON', 'victor.simon@mail.com', '242 Allée des Champs, 94000 Créteil'),
  ('André', 'GIRARD', 'andre.girard@mail.com', '453 Chemin de l''Église, 69006 Lyon'),
  ('Noémie', 'GAUTIER', 'noemie.gautier@mail.com', '574 Route des Érables, 75018 Paris'),
  ('Inès', 'BOYER', 'ines.boyer@mail.com', '715 Avenue Jean Jaurès, 31000 Toulouse'),
  ('Claudine', 'SCHMITT', 'claudine.schmitt@mail.com', '291 Avenue de la Colline, 93000 Bobigny'),
  ('Zoé', 'FRANCOIS', 'zoe.francois@mail.com', '439 Route Molière, 21000 Dijon'),
  ('Julie', 'JEAN', 'julie.jean@mail.com', '777 Rue de la Poste, 75011 Paris'),
  ('Guillaume', 'COLIN', 'guillaume.colin@mail.com', '172 Impasse de l''Avenir, 83100 Toulon'),
  ('Laurence', 'ROUX', 'laurence.roux@mail.com', '276 Rue Nationale, 31000 Toulouse'),
  ('Margot', 'MOREAU', 'margot.moreau@mail.com', '754 Impasse Saint-Michel, 75013 Paris'),
  ('Jacqueline', 'NICOLAS', 'jacqueline.nicolas@mail.com', '116 Place du Château, 37100 Tours'),
  ('Hélène', 'ROUSSEAU', 'helene.rousseau@mail.com', '477 Place des Chênes, 37000 Tours'),
  ('Laura', 'LACROIX', 'laura.lacroix@mail.com', '945 Place Nationale, 37100 Tours'),
  ('Loïc', 'MARTIN', 'loic.martin@mail.com', '169 Chemin du Port, 69006 Lyon'),
  ('Camille', 'MASSON', 'camille.masson@mail.com', '297 Avenue des Vignes, 75010 Paris'),
  ('Paul', 'PETIT', 'paul.petit@mail.com', '885 Chemin de la Liberté, 31200 Toulouse'),
  ('Christophe', 'ROBERT', 'christophe.robert@mail.com', '694 Boulevard de la Poste, 69002 Lyon'),
  ('Valérie', 'MULLER', 'valerie.muller@mail.com', '39 Allée de la Liberté, 37200 Tours'),
  ('Bernard', 'DUFOUR', 'bernard.dufour@mail.com', '621 Allée Voltaire, 67000 Strasbourg'),
  ('Hélène', 'FOURNIER', 'helene.fournier@mail.com', '318 Cours de la Poste, 76000 Rouen'),
  ('Louis', 'BERNARD', 'louis.bernard@mail.com', '104 Place de la Place, 13002 Marseille'),
  ('Guillaume', 'LAURENT', 'guillaume.laurent@mail.com', '625 Avenue de Verdun, 44300 Nantes'),
  ('Pauline', 'SCHMITT', 'pauline.schmitt@mail.com', '86 Place Victor Hugo, 75017 Paris'),
  ('Carlos', 'NOURI', 'carlos.nouri@mail.com', '447 Chemin de la Colline, 87100 Limoges'),
  ('Gabriel', 'GAUTIER', 'gabriel.gautier@mail.com', '911 Place de la Poste, 31000 Toulouse'),
  ('Éliane', 'COLIN', 'eliane.colin@mail.com', '657 Allée de la Rivière, 49100 Angers'),
  ('Virginie', 'ROCHE', 'virginie.roche@mail.com', '401 Rue de la Paix, 67000 Strasbourg'),
  ('Thierry', 'LEGRAND', 'thierry.legrand@mail.com', '48 Rue Pasteur, 75002 Paris'),
  ('Virginie', 'VIDAL', 'virginie.vidal@mail.com', '844 Avenue des Jardins, 06300 Nice'),
  ('Raphaël', 'MOREAU', 'raphael.moreau@mail.com', '454 Avenue Jean Jaurès, 17000 La Rochelle'),
  ('Luc', 'PICARD', 'luc.picard@mail.com', '424 Allée de la Colline, 86000 Poitiers'),
  ('Dominique', 'DUMONT', 'dominique.dumont@mail.com', '285 Avenue Jean Jaurès, 87100 Limoges'),
  ('Claire', 'LAMBERT', 'claire.lambert@mail.com', '893 Boulevard de la Liberté, 76100 Rouen'),
  ('Frédéric', 'MEUNIER', 'frederic.meunier@mail.com', '848 Impasse La Fontaine, 13008 Marseille'),
  ('Dominique', 'DUPUIS', 'dominique.dupuis@mail.com', '671 Impasse des Jardins, 63000 Clermont-Ferrand'),
  ('Anaïs', 'ROY', 'anais.roy@mail.com', '128 Boulevard de la République, 75005 Paris'),
  ('Laura', 'GARNIER', 'laura.garnier@mail.com', '803 Rue de Verdun, 87000 Limoges'),
  ('Salma', 'CELIK', 'salma.celik@mail.com', '43 Route des Peupliers, 17000 La Rochelle'),
  ('Romain', 'ROGER', 'romain.roger@mail.com', '929 Avenue du Centre, 29200 Brest'),
  ('Christophe', 'CARON', 'christophe.caron@mail.com', '710 Allée de la Liberté, 34000 Montpellier'),
  ('Ana', 'POPESCU', 'ana.popescu@mail.com', '556 Place du Château, 06300 Nice'),
  ('Caroline', 'CLEMENT', 'caroline.clement@mail.com', '739 Avenue de la République, 33100 Bordeaux'),
  ('Chloé', 'ROGER', 'chloe.roger@mail.com', '787 Cours du Général de Gaulle, 69006 Lyon'),
  ('Mathilde', 'ROBIN', 'mathilde.robin@mail.com', '753 Rue du Moulin, 44300 Nantes'),
  ('Christophe', 'FONTAINE', 'christophe.fontaine@mail.com', '754 Route Molière, 33000 Bordeaux'),
  ('Denis', 'CLEMENT', 'denis.clement@mail.com', '703 Rue des Peupliers, 86100 Poitiers'),
  ('Florian', 'ARNAUD', 'florian.arnaud@mail.com', '912 Boulevard du Commerce, 13001 Marseille'),
  ('Luc', 'AUBERT', 'luc.aubert@mail.com', '630 Boulevard de la Gare, 37200 Tours'),
  ('Martine', 'MOREL', 'martine.morel@mail.com', '219 Rue Jean Jaurès, 49100 Angers'),
  ('Stéphanie', 'LEFEVRE', 'stephanie.lefevre@mail.com', '706 Impasse des Tilleuls, 06100 Nice'),
  ('David', 'BRUNET', 'david.brunet@mail.com', '265 Cours du 8 Mai 1945, 92100 Boulogne-Billancourt'),
  ('David', 'BOURGEOIS', 'david.bourgeois@mail.com', '165 Boulevard de la Rivière, 75019 Paris'),
  ('Catherine', 'NOEL', 'catherine.noel@mail.com', '493 Cours des Fleurs, 59000 Lille'),
  ('Virginie', 'GAUTIER', 'virginie.gautier@mail.com', '802 Cours des Roses, 76100 Rouen'),
  ('Céline', 'BLANC', 'celine.blanc@mail.com', '610 Allée des Lilas, 63100 Clermont-Ferrand'),
  ('Ricardo', 'PEREZ', 'ricardo.perez@mail.com', '199 Impasse des Roses, 75017 Paris'),
  ('Paul', 'DUPONT', 'paul.dupont@mail.com', '510 Avenue des Jardins, 57000 Metz'),
  ('Xavier', 'PETIT', 'xavier.petit@mail.com', '161 Place Nationale, 69007 Lyon'),
  ('Nicolas', 'BRUN', 'nicolas.brun@mail.com', '519 Place du Port, 93000 Bobigny'),
  ('Philippe', 'MICHEL', 'philippe.michel@mail.com', '708 Rue Pasteur, 29280 Brest'),
  ('Samuel', 'LEMAIRE', 'samuel.lemaire@mail.com', '684 Avenue de la Gare, 33300 Bordeaux'),
  ('Martine', 'MULLER', 'martine.muller@mail.com', '538 Avenue Victor Hugo, 94200 Ivry-sur-Seine'),
  ('Maxime', 'DAVID', 'maxime.david@mail.com', '537 Chemin du Général de Gaulle, 57070 Metz'),
  ('Thomas', 'DUMAS', 'thomas.dumas@mail.com', '555 Avenue Jean Jaurès, 38700 Grenoble'),
  ('Loïc', 'SCHMITT', 'loic.schmitt@mail.com', '192 Avenue des Peupliers, 21000 Dijon'),
  ('Marine', 'LEROY', 'marine.leroy@mail.com', '443 Route François Mitterrand, 69006 Lyon'),
  ('Vincent', 'MOREL', 'vincent.morel@mail.com', '744 Avenue des Fleurs, 38000 Grenoble'),
  ('Svetlana', 'COSTA', 'svetlana.costa@mail.com', '324 Chemin du Marché, 44100 Nantes'),
  ('Quentin', 'ROUSSEAU', 'quentin.rousseau@mail.com', '233 Boulevard du Général de Gaulle, 92200 Neuilly-sur-Seine'),
  ('Océane', 'JEAN', 'oceane.jean@mail.com', '449 Impasse des Roses, 06300 Nice'),
  ('Jeanne', 'MORIN', 'jeanne.morin@mail.com', '731 Allée Racine, 75014 Paris'),
  ('Claire', 'LACROIX', 'claire.lacroix@mail.com', '989 Rue des Vignes, 92100 Boulogne-Billancourt'),
  ('Loïc', 'LEMAIRE', 'loic.lemaire@mail.com', '111 Allée de la Victoire, 75013 Paris'),
  ('Jérôme', 'LEGRAND', 'jerome.legrand@mail.com', '840 Chemin du 8 Mai 1945, 51100 Reims'),
  ('Vincent', 'GARNIER', 'vincent.garnier@mail.com', '220 Cours du Soleil, 80090 Amiens'),
  ('Virginie', 'PICARD', 'virginie.picard@mail.com', '11 Route du Moulin, 75012 Paris'),
  ('Camille', 'DENIS', 'camille.denis@mail.com', '266 Chemin des Chênes, 94200 Ivry-sur-Seine'),
  ('Xavier', 'MARCHAND', 'xavier.marchand@mail.com', '799 Boulevard de Verdun, 67000 Strasbourg'),
  ('Louis', 'DURAND', 'louis.durand@mail.com', '380 Allée de l''Église, 75011 Paris'),
  ('Manon', 'LAMBERT', 'manon.lambert@mail.com', '821 Cours du Soleil, 75008 Paris'),
  ('Michel', 'PICARD', 'michel.picard@mail.com', '345 Cours des Érables, 44100 Nantes'),
  ('Léo', 'BRUNET', 'leo.brunet@mail.com', '537 Rue de l''Église, 34070 Montpellier'),
  ('Fabrice', 'PETIT', 'fabrice.petit@mail.com', '589 Place de la Paix, 63000 Clermont-Ferrand'),
  ('Chloé', 'BOYER', 'chloe.boyer@mail.com', '664 Cours de la Mairie, 93200 Saint-Denis'),
  ('Amina', 'KOWALSKI', 'amina.kowalski@mail.com', '536 Cours des Écoles, 75018 Paris'),
  ('Claire', 'ROLLAND', 'claire.rolland@mail.com', '727 Boulevard de la Gare, 80000 Amiens'),
  ('Théo', 'ROBIN', 'theo.robin@mail.com', '512 Chemin du Général de Gaulle, 76600 Rouen'),
  ('Robert', 'LEMAIRE', 'robert.lemaire@mail.com', '504 Boulevard de l''Avenir, 72100 Le Mans'),
  ('Dominique', 'RENAUD', 'dominique.renaud@mail.com', '955 Cours du Commerce, 06200 Nice'),
  ('Gérard', 'LEROY', 'gerard.leroy@mail.com', '760 Avenue Pasteur, 83100 Toulon'),
  ('Jean', 'BARBIER', 'jean.barbier@mail.com', '735 Chemin des Peupliers, 93100 Montreuil'),
  ('Jérôme', 'ANDRE', 'jerome.andre@mail.com', '768 Cours du Centre, 69007 Lyon'),
  ('Amélie', 'ROLLAND', 'amelie.rolland@mail.com', '584 Avenue Notre-Dame, 33100 Bordeaux'),
  ('Joséphine', 'AUBERT', 'josephine.aubert@mail.com', '814 Impasse des Tilleuls, 33000 Bordeaux'),
  ('Alexandre', 'GIRAUD', 'alexandre.giraud@mail.com', '484 Chemin Notre-Dame, 31000 Toulouse'),
  ('Valérie', 'MASSON', 'valerie.masson@mail.com', '684 Allée du 8 Mai 1945, 57000 Metz'),
  ('Baptiste', 'BERTRAND', 'baptiste.bertrand@mail.com', '991 Boulevard des Chênes, 31000 Toulouse'),
  ('Catherine', 'DUPONT', 'catherine.dupont@mail.com', '680 Cours de la Gare, 49000 Angers'),
  ('Corinne', 'ROUSSEL', 'corinne.roussel@mail.com', '530 Chemin de l''Église, 13006 Marseille'),
  ('Stéphane', 'BRUNET', 'stephane.brunet@mail.com', '339 Rue Nationale, 06300 Nice'),
  ('Lucas', 'DURAND', 'lucas.durand@mail.com', '266 Route Racine, 51430 Reims'),
  ('Mathieu', 'DAVID', 'mathieu.david@mail.com', '374 Allée des Champs, 93100 Montreuil'),
  ('Julien', 'MICHEL', 'julien.michel@mail.com', '927 Avenue des Écoles, 75019 Paris'),
  ('Lucie', 'BOYER', 'lucie.boyer@mail.com', '573 Avenue Victor Hugo, 59200 Lille'),
  ('Éliane', 'FAURE', 'eliane.faure@mail.com', '500 Impasse de la Victoire, 75003 Paris'),
  ('Léo', 'MARCHAND', 'leo.marchand@mail.com', '617 Boulevard de l''Église, 75016 Paris'),
  ('Monique', 'MEUNIER', 'monique.meunier@mail.com', '205 Impasse des Écoles, 63000 Clermont-Ferrand'),
  ('Suzanne', 'JOLY', 'suzanne.joly@mail.com', '398 Rue du 11 Novembre, 67100 Strasbourg'),
  ('Yves', 'CHEVALIER', 'yves.chevalier@mail.com', '204 Avenue de l''Église, 33100 Bordeaux'),
  ('Delphine', 'MARTIN', 'delphine.martin@mail.com', '455 Allée des Champs, 75018 Paris'),
  ('Claudine', 'ANDRE', 'claudine.andre@mail.com', '143 Chemin du Parc, 13002 Marseille'),
  ('Loïc', 'GIRARD', 'loic.girard@mail.com', '415 Route de la Place, 75012 Paris'),
  ('Valentin', 'RENAUD', 'valentin.renaud@mail.com', '876 Chemin de l''Église, 25000 Besançon'),
  ('Virginie', 'PETIT', 'virginie.petit@mail.com', '812 Place du Port, 45100 Orléans'),
  ('Lucie', 'LEFEVRE', 'lucie.lefevre@mail.com', '636 Impasse de la Liberté, 25480 Besançon'),
  ('Inès', 'DURAND', 'ines.durand@mail.com', '792 Route de la Poste, 57070 Metz'),
  ('Véronique', 'LAURENT', 'veronique.laurent@mail.com', '91 Place du Centre, 72000 Le Mans'),
  ('Gabriel', 'MICHEL', 'gabriel.michel@mail.com', '662 Rue des Roses, 87100 Limoges'),
  ('Patrick', 'GERARD', 'patrick.gerard@mail.com', '669 Impasse de la Place, 83200 Toulon'),
  ('Romain', 'ROUSSEL', 'romain.roussel@mail.com', '421 Route de la Mairie, 51430 Reims'),
  ('Sarah', 'RENARD', 'sarah.renard@mail.com', '926 Route des Peupliers, 44300 Nantes'),
  ('Caroline', 'LEMOINE', 'caroline.lemoine@mail.com', '318 Avenue des Lilas, 83000 Toulon'),
  ('Frédéric', 'ROLLAND', 'frederic.rolland@mail.com', '439 Avenue du Château, 94000 Créteil'),
  ('Martin', 'GERARD', 'martin.gerard@mail.com', '948 Allée des Tilleuls, 25000 Besançon'),
  ('Bruno', 'LEFEVRE', 'bruno.lefevre@mail.com', '538 Route de l''Église, 51520 Reims'),
  ('Vincent', 'ROBERT', 'vincent.robert@mail.com', '922 Avenue des Roses, 76000 Rouen'),
  ('Sophie', 'BOYER', 'sophie.boyer@mail.com', '930 Route des Peupliers, 13001 Marseille'),
  ('Thierry', 'MATHIEU', 'thierry.mathieu@mail.com', '573 Avenue Saint-Michel, 06100 Nice'),
  ('Monique', 'LEFEVRE', 'monique.lefevre@mail.com', '4 Rue Pasteur, 13008 Marseille'),
  ('Christian', 'FAURE', 'christian.faure@mail.com', '50 Chemin Saint-Michel, 75002 Paris'),
  ('Simone', 'MERCIER', 'simone.mercier@mail.com', '259 Place des Érables, 72100 Le Mans'),
  ('Julie', 'BERNARD', 'julie.bernard@mail.com', '656 Avenue Clémenceau, 33000 Bordeaux'),
  ('Amélie', 'BRUNET', 'amelie.brunet@mail.com', '464 Cours Georges Pompidou, 72100 Le Mans'),
  ('Aurélie', 'LEROY', 'aurelie.leroy@mail.com', '27 Chemin de la Place, 35200 Rennes'),
  ('Simon', 'LECLERCQ', 'simon.leclercq@mail.com', '672 Chemin du Moulin, 69007 Lyon'),
  ('Martine', 'ROUSSEL', 'martine.roussel@mail.com', '975 Allée des Peupliers, 69002 Lyon'),
  ('Nicole', 'LECLERCQ', 'nicole.leclercq@mail.com', '157 Cours Voltaire, 37000 Tours'),
  ('Paul', 'PHILIPPE', 'paul.philippe@mail.com', '283 Chemin Victor Hugo, 57070 Metz'),
  ('Caroline', 'BRUN', 'caroline.brun@mail.com', '333 Chemin des Érables, 63000 Clermont-Ferrand'),
  ('Jade', 'VINCENT', 'jade.vincent@mail.com', '166 Allée des Lilas, 75004 Paris'),
  ('Victoire', 'GAUTHIER', 'victoire.gauthier@mail.com', '203 Cours des Roses, 75020 Paris'),
  ('Éric', 'CLEMENT', 'eric.clement@mail.com', '747 Chemin Nationale, 51520 Reims'),
  ('Quentin', 'OLIVIER', 'quentin.olivier@mail.com', '461 Route du 11 Novembre, 75019 Paris'),
  ('Jacques', 'RENAUD', 'jacques.renaud@mail.com', '418 Impasse des Chênes, 29280 Brest'),
  ('Julie', 'GUERIN', 'julie.guerin@mail.com', '156 Place de la Forêt, 72100 Le Mans'),
  ('Clément', 'JOLY', 'clement.joly@mail.com', '649 Chemin de l''Église, 25480 Besançon'),
  ('Philippe', 'MORIN', 'philippe.morin@mail.com', '573 Rue du Château, 34090 Montpellier'),
  ('Marc', 'BERTRAND', 'marc.bertrand@mail.com', '863 Place François Mitterrand, 59000 Lille'),
  ('René', 'PIERRE', 'rene.pierre@mail.com', '916 Cours Pasteur, 35000 Rennes'),
  ('Dominique', 'DUMONT', 'dominique.dumont@mail.com', '173 Chemin des Jardins, 67100 Strasbourg'),
  ('Ricardo', 'FERRARI', 'ricardo.ferrari@mail.com', '791 Place Jean Jaurès, 94100 Saint-Maur'),
  ('Marco', 'CONTI', 'marco.conti@mail.com', '767 Place de la Liberté, 63100 Clermont-Ferrand'),
  ('Yasmine', 'RICCI', 'yasmine.ricci@mail.com', '40 Cours de la République, 75003 Paris'),
  ('Julien', 'MATHIEU', 'julien.mathieu@mail.com', '547 Boulevard des Jardins, 75003 Paris'),
  ('Madeleine', 'MORIN', 'madeleine.morin@mail.com', '849 Allée du 8 Mai 1945, 75002 Paris'),
  ('Mathis', 'MARCHAND', 'mathis.marchand@mail.com', '929 Chemin du Commerce, 69003 Lyon'),
  ('Nicole', 'BOURGEOIS', 'nicole.bourgeois@mail.com', '210 Avenue Pasteur, 37100 Tours'),
  ('Hugo', 'MULLER', 'hugo.muller@mail.com', '912 Route Saint-Michel, 25000 Besançon'),
  ('Antoine', 'GARNIER', 'antoine.garnier@mail.com', '281 Impasse de l''Église, 31300 Toulouse'),
  ('Quentin', 'MARCHAND', 'quentin.marchand@mail.com', '964 Chemin des Jardins, 34070 Montpellier'),
  ('Miguel', 'RUSSO', 'miguel.russo@mail.com', '21 Place de la Gare, 44100 Nantes'),
  ('Paul', 'ROY', 'paul.roy@mail.com', '598 Route de la République, 67000 Strasbourg'),
  ('Antoine', 'ROUSSEL', 'antoine.roussel@mail.com', '358 Impasse des Jardins, 75005 Paris'),
  ('Delphine', 'LEMOINE', 'delphine.lemoine@mail.com', '838 Impasse des Jardins, 86100 Poitiers'),
  ('Émilie', 'MARIE', 'emilie.marie@mail.com', '223 Route de l''Avenir, 29280 Brest'),
  ('Chloé', 'LACROIX', 'chloe.lacroix@mail.com', '899 Allée de la Rivière, 92100 Boulogne-Billancourt'),
  ('Louis', 'GAILLARD', 'louis.gaillard@mail.com', '537 Place de la Victoire, 75014 Paris'),
  ('Samir', 'YILMAZ', 'samir.yilmaz@mail.com', '854 Avenue Saint-Michel, 06000 Nice'),
  ('Christian', 'LEMOINE', 'christian.lemoine@mail.com', '327 Cours La Fontaine, 75002 Paris'),
  ('Simone', 'ROGER', 'simone.roger@mail.com', '794 Rue des Champs, 69003 Lyon'),
  ('Guillaume', 'HENRY', 'guillaume.henry@mail.com', '256 Route des Champs, 72000 Le Mans'),
  ('Laurence', 'FABRE', 'laurence.fabre@mail.com', '957 Route des Écoles, 75020 Paris'),
  ('Thomas', 'ROBIN', 'thomas.robin@mail.com', '648 Place des Lilas, 75001 Paris'),
  ('Sarah', 'DUPONT', 'sarah.dupont@mail.com', '464 Rue des Peupliers, 83200 Toulon'),
  ('Victor', 'ROUSSEAU', 'victor.rousseau@mail.com', '159 Avenue des Vignes, 14000 Caen'),
  ('Isabella', 'MARTINEZ', 'isabella.martinez@mail.com', '552 Avenue des Érables, 59200 Lille'),
  ('Bernard', 'MORIN', 'bernard.morin@mail.com', '601 Place Racine, 14000 Caen'),
  ('Alain', 'GAUTHIER', 'alain.gauthier@mail.com', '856 Rue Georges Pompidou, 44300 Nantes'),
  ('Juliette', 'CHEVALIER', 'juliette.chevalier@mail.com', '338 Cours du Parc, 13001 Marseille'),
  ('Bruno', 'MARIE', 'bruno.marie@mail.com', '13 Place Georges Pompidou, 33300 Bordeaux'),
  ('Camille', 'PERRIN', 'camille.perrin@mail.com', '414 Chemin Nationale, 34070 Montpellier'),
  ('Marie', 'GARNIER', 'marie.garnier@mail.com', '308 Allée du Marché, 37200 Tours'),
  ('Catherine', 'LEROY', 'catherine.leroy@mail.com', '647 Avenue Notre-Dame, 31100 Toulouse'),
  ('Juliette', 'JEAN', 'juliette.jean@mail.com', '214 Boulevard des Érables, 21000 Dijon'),
  ('Raphaël', 'DUMAS', 'raphael.dumas@mail.com', '648 Cours Clémenceau, 87100 Limoges'),
  ('Laurent', 'MICHEL', 'laurent.michel@mail.com', '631 Allée de la Forêt, 75001 Paris'),
  ('Margot', 'ROBIN', 'margot.robin@mail.com', '620 Avenue du Général de Gaulle, 49000 Angers'),
  ('Lucie', 'BRUN', 'lucie.brun@mail.com', '299 Rue Notre-Dame, 59000 Lille'),
  ('Lucas', 'VINCENT', 'lucas.vincent@mail.com', '361 Place du 11 Novembre, 94100 Saint-Maur'),
  ('Marine', 'LECLERC', 'marine.leclerc@mail.com', '490 Rue du Marché, 59100 Lille'),
  ('Camille', 'LEGRAND', 'camille.legrand@mail.com', '658 Rue du Commerce, 59000 Lille'),
  ('Brigitte', 'CHEVALIER', 'brigitte.chevalier@mail.com', '548 Rue des Lilas, 87100 Limoges'),
  ('Clément', 'FONTAINE', 'clement.fontaine@mail.com', '793 Route des Tilleuls, 92000 Nanterre'),
  ('Léo', 'LAURENT', 'leo.laurent@mail.com', '429 Route des Fleurs, 69006 Lyon'),
  ('Caroline', 'DUFOUR', 'caroline.dufour@mail.com', '88 Route du Centre, 13001 Marseille'),
  ('Bernard', 'LACROIX', 'bernard.lacroix@mail.com', '251 Impasse Saint-Michel, 75009 Paris'),
  ('Mathis', 'BERTRAND', 'mathis.bertrand@mail.com', '201 Allée Voltaire, 69003 Lyon'),
  ('Élise', 'GARNIER', 'elise.garnier@mail.com', '201 Impasse des Champs, 35000 Rennes'),
  ('Anne', 'FAURE', 'anne.faure@mail.com', '739 Rue du Port, 51100 Reims'),
  ('Claire', 'MARCHAND', 'claire.marchand@mail.com', '832 Avenue du Port, 33100 Bordeaux'),
  ('Hugo', 'BOURGEOIS', 'hugo.bourgeois@mail.com', '871 Cours Racine, 80000 Amiens'),
  ('Anaïs', 'MARTIN', 'anais.martin@mail.com', '169 Rue de la Gare, 06000 Nice'),
  ('Denis', 'ROLLAND', 'denis.rolland@mail.com', '103 Cours des Tilleuls, 75013 Paris'),
  ('Philippe', 'ROUSSEAU', 'philippe.rousseau@mail.com', '173 Impasse des Jardins, 49100 Angers'),
  ('Robert', 'LAURENT', 'robert.laurent@mail.com', '214 Boulevard du Port, 06300 Nice'),
  ('Margot', 'DUVAL', 'margot.duval@mail.com', '939 Impasse Saint-Michel, 06100 Nice'),
  ('André', 'GAUTHIER', 'andre.gauthier@mail.com', '288 Chemin du Commerce, 86100 Poitiers'),
  ('Zoé', 'NOEL', 'zoe.noel@mail.com', '861 Cours des Écoles, 93100 Montreuil'),
  ('Nathalie', 'DUBOIS', 'nathalie.dubois@mail.com', '287 Impasse de l''Avenir, 59000 Lille'),
  ('Agnès', 'BLANC', 'agnes.blanc@mail.com', '227 Chemin de la Rivière, 75012 Paris'),
  ('Guillaume', 'MOREAU', 'guillaume.moreau@mail.com', '91 Cours des Tilleuls, 06100 Nice'),
  ('Émilie', 'LECLERCQ', 'emilie.leclercq@mail.com', '382 Place Jean Jaurès, 21800 Dijon'),
  ('Noémie', 'ROUSSEAU', 'noemie.rousseau@mail.com', '878 Route des Fleurs, 49000 Angers'),
  ('Frédéric', 'CLEMENT', 'frederic.clement@mail.com', '973 Place du Général de Gaulle, 29200 Brest'),
  ('Valentin', 'SIMON', 'valentin.simon@mail.com', '877 Avenue de la Place, 14200 Caen'),
  ('Margot', 'DUMAS', 'margot.dumas@mail.com', '657 Rue des Champs, 75011 Paris'),
  ('Mathilde', 'GAILLARD', 'mathilde.gaillard@mail.com', '449 Route du 11 Novembre, 75002 Paris'),
  ('Mathis', 'RICHARD', 'mathis.richard@mail.com', '899 Place François Mitterrand, 25480 Besançon'),
  ('Aurélie', 'GERARD', 'aurelie.gerard@mail.com', '221 Place de la Gare, 31000 Toulouse'),
  ('Frédéric', 'ARNAUD', 'frederic.arnaud@mail.com', '119 Cours Clémenceau, 37100 Tours'),
  ('Pascal', 'CARON', 'pascal.caron@mail.com', '113 Route de la Forêt, 80090 Amiens'),
  ('Christian', 'RICHARD', 'christian.richard@mail.com', '485 Avenue de la République, 06000 Nice');