# ServiceAccount pour Jenkins - utilisé pour les déploiements CD
# Ce compte est limité aux opérations nécessaires sur le namespace rhdemo-stagingkub
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-deployer
  namespace: rhdemo-stagingkub
  labels:
    app.kubernetes.io/name: jenkins-deployer
    app.kubernetes.io/component: ci-cd
    app.kubernetes.io/managed-by: manual
---
# Secret pour stocker le token du ServiceAccount (requis depuis K8s 1.24+)
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-deployer-token
  namespace: rhdemo-stagingkub
  annotations:
    kubernetes.io/service-account.name: jenkins-deployer
  labels:
    app.kubernetes.io/name: jenkins-deployer
    app.kubernetes.io/component: ci-cd
type: kubernetes.io/service-account-token
